# Generated by Django 5.2.11 on 2026-03-07 17:03

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PAID', 'Pagado')], default='PENDING', max_length=20)),
                ('delivery_status', models.CharField(choices=[('PENDING', 'Pendiente'), ('DELIVERED', 'Entregado')], default='PENDING', max_length=20)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='customers.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('CASH', 'Efectivo'), ('TRANSFER', 'Transferencia'), ('APP', 'DeUna')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('paid_at', models.DateTimeField()),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.sale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleBagItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price_charged', models.DecimalField(decimal_places=2, max_digits=6)),
                ('bag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resources.bag')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bag_items', to='sales.sale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleDryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intervals', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price_charged', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dryer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resources.dryer')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dry_items', to='sales.sale')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleWashItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_charged', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wash_items', to='sales.sale')),
                ('washer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resources.washer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SaleWashSupply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price_charged', models.DecimalField(decimal_places=2, max_digits=6)),
                ('portion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='resources.supplyportion')),
                ('wash_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplies', to='sales.salewashitem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
